services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.3-fpm
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
      - composer

  composer:
    image: composer
    command: bash -c "composer install --ignore-platform-reqs"
    volumes:
      - ./:/app

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=cybersecurity
      - POSTGRES_USER=cybersecurity